name: HealthData
url: healthdata-example.interra.io
identifier: healthdata
schema: pod-full
description: 'This was a lot of work'
front-page-icon-collection: theme
front-page-icons:
 - city-planning
 - finance-and-budgeting
 - health-care
 - public-safety
 - transportation
 - education
