name: Project Open Data Full Specification
collections:
  - dataset
  - organization
  - distribution
  - keyword
  - license
  - theme
facets:
    - keyword
    - theme
    # TODO: Add ability to go down a level for format.
#    - distribution:format
references:
  dataset:
      # field: referenced collection
      publisher: organization
      distribution: distribution
