name: Project Open Data Full Specification
collections:
  - dataset
  - organization
  - distribution
  - keyword
  - license
  - theme
facets:
    keyword:
      label: Tags
      field: keyword
    theme:
      label: Category
      field: theme
    publisher:
      label: Organization
      field: publisher.name
    format:
      label: format
      field: distribution.format
references:
  dataset:
      # field: referenced collection
      publisher: organization
      distribution: distribution
