'@type': 'dcat:Dataset'
contactPoint:
  fn: admin
  hasEmail: 'mailto:HealthData@hhs.gov'
description: "<p>This dataset represents a subset of the products developed by commercial partners using NIH and FDA inventions and technologies</p>\n"
distribution:
  - {interra-reference: widget-06dc7cac-92b5-4cf8-ab51-8e4af814ef86}
identifier: b0bb9288-ad10-4d79-8a13-1e0fbaf80962
keyword:
  - biomedical
  - collaboration
  - innovation
  - invention
  - licensing
  - materials
  - medical
  - nih
  - patents
  - 'product development'
  - products
  - research
  - technology
language:
  - en
license: 'http://opendefinition.org/licenses/odc-odbl/'
modified: '2016-05-02'
publisher:
  interra-reference: national-institutes-of-health-nih-department-of-health-andamp-human-services
temporal: '1980-12-31T19:00:00-05:00/2017-08-01T02:17:30-04:00'
title: 'Products developed using NIH and FDA inventions'
programCode:
  - '009:000'
accessLevel: public
