'@type': 'dcat:Dataset'
accessLevel: public
bureauCode:
  - '009:25'
contactPoint:
  fn: 'NLM TEHIP'
  hasEmail: 'mailto:tehip@teh.nlm.nih.gov'
description: "<p>TOXMAP® is a Geographic Information System (GIS) that uses maps of the United States and Canada to help users visually explore data primarily from the EPA's Toxics Release Inventory (TRI) and Superfund Program, as well as some non-EPA datasets. TOXMAP helps users create nationwide, regional, or local area maps showing where TRI chemicals are released on-site into the air, water, and ground. It also provides facility and release details, color-codes release amounts for a single year or year range, and aggregates release data over multiple years. Maps also show locations of Superfund National Priorities List (NPL) sites, listing all chemical contaminants present at these sites.  Two versions of TOXMAP are available: the classic version of TOXMAP released in 2004, and a new version of TOXMAP based on Adobe® Flash/Flex technology.  The new version provides an improved map appearance and interactive capabilities and additional datasets such as EPA coal plant emissions data and U.S. commercial nuclear power plants.</p>\n"
distribution:
  - {interra-reference: api-1e39e4a1-6095-4aa1-8c00-b6d49d3eb678}
  - {interra-reference: widget-fe762fa5-c63a-4675-9cba-9edac7b391a0}
  - {interra-reference: api-1e39e4a1-6095-4aa1-8c00-b6d49d3eb678}
identifier: 18f156d5-a5ce-4a36-9b25-8acc109911b4
keyword:
  - 'chemical map'
  - 'community health'
  - 'environmental health'
  - 'environmental map'
  - 'hazardous substances'
  - 'nuclear power plants'
  - pollution
  - 'power plants'
  - superfund
  - 'toxics release inventory'
  - tri
language:
  - en
modified: '2016-09-16'
publisher:
  interra-reference: national-library-of-medicine-nlm
temporal: '1987-12-31T19:00:00-05:00/2013-12-30T19:00:00-05:00'
title: 'TOXMAP®: Environmental Health Maps'
programCode:
  - '009:000'
